### ISSUE TITLE
producer restore (question)

### ISSUE THREAD

**Issue by podollb** [Netflix/hollow#114]
After doing a `restore` on the producer side, is there anyway to get the data from the producer (back into my domain objects)?

For example, if my app allows CRUD operations on a `List<Person>` that it holds in memory. And my producer writes that out (upon any change to my `List<Person>` I give the list to hollow to write/produce). All is fine.

But now, when I restart my app, I do a producer **restore**, so the producer is back up-to-date, _but_ is there anyway to load my `List<Person>` back up? Or do I have to create a consumer (in my producer project) that can consume things back (only on startup) just to get my `List<Person>` hydrated again.

Because if I don't load my `List<Person>` back up, the next time a CRUD operation occurs, I'll basically be wiping out my data when I give the `List<Person>` to the producer to write/produce. 

Maybe that is a stupid question and makes no sense, but hopefully not...

**Comment by rpalcolea** [comment]
@podollb ,

I don't think there's a out of the box solution for this in Hollow.

However, I think you could use the Incremental Producer and write deltas. 

For example, let's say you have this POJO:

```
public class Person {
   public long id;
   public String name;

   public Person(long id, String name) {
     this.id = id;
     this.name = name;
   }
}
```

If you write to Hollow a `List` of `Person` let's say:

```
HollowIncrementalProducer incrementalProducer = new HollowIncrementalProducer(producer);
incrementalProducer.addOrModify(new Person(1, "Roberto"));
incrementalProducer.addOrModify(new Person(2, "Gina"));
incrementalProducer.runCycle();
```

This will write those two person to Hollow. Then if you restart your producer and restore, you would have those.

And then if you write more persons:

```
HollowIncrementalProducer incrementalProducer = new HollowIncrementalProducer(producer);
incrementalProducer.addOrModify(new Person(3, "MyName"));
incrementalProducer.addOrModify(new Person(4, "Hollow"));
incrementalProducer.runCycle();
```

It will keep the old records and store the new ones because the incremental producer attaches all the objects from the previous cycle (https://github.com/Netflix/hollow/blob/b35bb2a7050fa824a255021669f1fd41a2792659/hollow/src/main/java/com/netflix/hollow/api/producer/HollowIncrementalProducer.java#L83) then removes and adds records for the new state (delta).

Don't know if the above is doable on your use case, if you have something like 

```
public class OtherClass {
   public Set<Person> persons;
}
```

And you want to maintain the state of the `Set`, then I think you would need to explore if the incremental is doable for that.. haven't tried that, I'd suggest asking in the Gitter room (https://gitter.im/Netflix/hollow?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)... perhaps @dkoszewnik or @toolbear have better ideas for this

**Comment by ghost** [comment]
@podollb 

Thanks for your question. It's a good question, one we've encountered from other teams at Netflix. It may indicate a gap in our documentation.

In general, the design of Hollow assumes your producer has a source-of-truth other than the Hollow data states it produces, i.e. other than itself. The design of `HollowProducer` is geared in this way, specifically the requirement that you populate the entire dataset every cycle (and Hollow determines what, if anything, has changed).

The assumption also manifests with the POJO-based data model used on the producer. Hollow provides no direct mechanism for rehydrating producer POJOs from a consumed data state. Our biggest use-case, and one of the reasons Hollow exists, is because we have datasets large enough that keeping the entire data state as POJOs in memory is unwieldy. The assumed pattern is to iterate over your source of truth, mint a POJO on the fly, add it to the write state, and discard the POJO.

Another way of saying this is that Hollow is a disseminated total cache and, like other caching solutions, they are typically backed by some other source of truth. Unlike other caching solutions, consumers have the entire dataset in memory so it's easy to start thinking of Hollow like a database and its own source-of-truth. And, just as you could use a caching solution (if it's durable) as a source of truth, you can use Hollow that way, but it is going against the grain somewhat.

A potential gotcha of using the producer as it's own source of truth is eventual consistency on your announced states. If, for instance, every cycle rehydrated POJOs from the previously announced state, it's possible delays in announcement propagation will get you out of sync. Technically this is possible even for the normal restore case; but we assume the probability is low because a server restart or new deploy are long enough that the latest announcement will be consistent by the time we're ready to restore.

As @rpalcolea mentions, the `HollowIncrementalProducer` makes some inroads on the producer-as-source-of-truth use-case, though that isn't our driver for the feature. It's a beta API subject to change, but you can achieve similar results following the advice under [Delta-Based Producer Input](http://hollow.how/advanced-topics/#delta-based-producer-input). Either approach are good fits when you want to do the bookkeeping yourself of what's changed versus relying on Hollow to figure it out.

I'm going to close this for now. Feel free to reply with more questions and re-open if you don't feel we answered you. As mentioned, we're available to [chat on Gitter](https://gitter.im/Netflix/hollow) as well.
