### ISSUE TITLE
Confuse on using HollowIncrementalProducer

### ISSUE THREAD

**Issue by maiakhoa** [Netflix/hollow#137]
Hi @dkoszewnik 
Can you help me explain this case?
I've tried to rewrite addOrModify method in **HollowIncrementalProducer** like this

```
public void addOrModify(Object obj) {
    RecordPrimaryKey pk = newState.getObjectMapper().extractPrimaryKey(obj);
    int oldOrdinal = getOrdinalRecord(newState.getPriorState().getStateEngine(), pk);

    int newOrdinal = newState.add(obj);
    if (oldOrdinal != -1 && newOrdinal != oldOrdinal) {
        delete(pk);
    }
}
```

Just run deleting at the final step.
Meaning I want to avoid store objects in mutations map because it cost a lot of memory. But when I did that, the data is messed up like fields become a primary key. Could you help me explain this or do you have a solution to avoid store so many objects in mutation map?

Thanks

**Comment by ghost** [comment]
Hi @maiakhoa. Our thinking for the `HollowIncrementalProducer` was to streamline the use-case where you would otherwise follow the guidance in [Delta-Based Producer Input](http://hollow.how/advanced-topics/#delta-based-producer-input) by accumulating changes in RAM. To avoid too much accumulation, you would either run cycles frequently enough (e.g. every N minutes on a set cadence) or keep track of modifications and run cycles once a threshold was reached (e.g. run a cycle every 1000 mutations).

We were also guarding against lost mutations. A naive implementation we discarded early on would have essentially done this:

1. finish a cycle, then immediately call `newState.getStateEngine().addAllObjectsFromPreviousCycle()`
2. call `addOrModify` or `delete` for events as they came in
3. call `runCycle` every so often
4. go to 1

One problem is cycle failure. It's possible for the cycle to fail, in which case we've lost all of the mutation events that came in. Unless there's a mechanism to reliably replay those events we've either lost data or we have to a traditional `HollowProducer` *add the world* cycle from the source-of-truth.

A second problem has to do with multiple events for the same primary key. These have to be deduped.

Both problems are sidestepped by using a `Map<PrimaryKey,POJO>` though it does limit utility to those cases which can fit all mutations for a single cycle on the heap.

**Comment by ghost** [comment]
This doesn't work as expected:

```
    int oldOrdinal = getOrdinalRecord(newState.getPriorState().getStateEngine(), pk);

    int newOrdinal = newState.add(obj);
    if (oldOrdinal != -1 && newOrdinal != oldOrdinal) {
        delete(pk);
    }
```

Because `newState.add(obj)` will always return a different ordinal if `obj` being added differs from the previous cycle. However, the primary key will match. You have in effect, added a modification to the write state immediately, then queued up a deletion of a record matching the primary key to be removed when `runCycle` is called.

**Comment by ghost** [comment]
I will close this issue for now. Feel free to re-open if you have more questions.

**Comment by maiakhoa** [comment]
thank you so much @toolbear

**Comment by tinetti** [comment]
Related comments here: https://github.com/Netflix/hollow/issues/155
