### ISSUE TITLE
Diff tool should differentiate between null values and empty collections

### ISSUE THREAD

**Issue by ghost** [Netflix/hollow#166]
When a collections field changes from `null` to a reference to Set|List|Map that is empty, the Diff and History UIs detect this as a difference, but then present no difference in the UI. Surface in the UI that the field changed from null to an empty collection (or vice versa).

**Comment by akhaku** [comment]
There are a couple ways we can handle this. We can choose to start explicitly displaying `null` with the type name (for every nullable value that is null) instead of doing nothing, or we can explicitly say when a field is empty (has no children in its hierarchy).
I'll put up a PR for the former version for now. It's trivial to change it to do the latter, or even a combination of the two. Let me know what you think!
