### ISSUE TITLE
HollowWriteStateEnginePrimaryKeyHasher is not hashing correctly

### ISSUE THREAD

**Issue by flore77** [Netflix/hollow#309]
I noticed there is a problem with hashing for objects with primary keys.

I have the following classes:
```java
class A {
   Map<B, C> map;
}

@HollowPrimaryKey{...}
class B {...}

class C {...}
```

The problem appears when trying to write the snapshot, `HollowWriteStateEnginePrimaryKeyHasher` tries to hash the `B` objects by the fields specified in the `@HollowPrimaryKey` annotation, but it fails due to incorrect retrieving the fields values.

The navigateToField method https://github.com/Netflix/hollow/blob/4796e71e68e6494cc39bc34815d0dc1d8fd05401/hollow/src/main/java/com/netflix/hollow/core/write/HollowWriteStateEnginePrimaryKeyHasher.java#L86-L88
computes incorrectly the offset. Instead of using `i` to compute the offset of the fields before the desired field, it always uses `fieldIdx`. 

It seems the solution would be to replace: `switch(schema.getFieldType(fieldIdx))` -> `switch(schema.getFieldType(i))`

**Comment by dkoszewnik** [comment]
@flore77 I think you're right.  Getting the right fix will be tricky, because a fix may change the hash ordering of affected sets and maps.  This will likely cause the hash of these records to change, and will fail the integrity check step of subsequent publishes from the `HollowProducer` for existing delta chains.  Adding @toolbear for visibility.

**Comment by PaulSandoz** [comment]
I confirmed this will cause integrity checking to fail, but perhaps it's also likely to fail when publishing since a corrupt ordinal will be read resulting in some index out of bounds exception. I am presuming if it does not fail in publishing then the data the corrupt ordinal points to will be stable, if not then that might also result in integrity checking to fail?

**Comment by flore77** [comment]
> it's also likely to fail when publishing since a corrupt ordinal will be read resulting in some index out of bounds exception

While playing around with it, I have indeed received `IndexOutOfBoundsException` and also `NullPointerException`.

**Comment by PaulSandoz** [comment]
Merged into the hollow4 branch
