### ISSUE TITLE
Build tools plugin for generating consumer api

### ISSUE THREAD

**Issue by IgorPerikov** [Netflix/hollow#31]
**UPDATE**
**Build plugins are developing as a standalone projects**:
- [gradle plugin](https://github.com/nebula-plugins/nebula-hollow-plugin)
- [maven plugin](https://github.com/IgorPerikov/hollow-maven-plugin)

Hi! When I was generating consumer api, the first thought I had - there must be a gradle/maven plugin for doing that. I think that executing or embedding java code to generate part of source code is not very convenient. So if the team will find this useful too, I would like to participate and create them. 

Plugin will be configurable with:

- apiClassName
- packageName
- packagesToScan

I see plugin's core part something like that:
```
HollowWriteStateEngine writeEngine = new HollowWriteStateEngine();
HollowObjectMapper mapper = new HollowObjectMapper(writeEngine);
Collection<Class<?>> datamodelClasses = retrieveClasses();
for (Class<?> clazz : datamodelClasses) {
    mapper.initializeTypeState(clazz);
}
String directory = buildDirectoryPath(packageName);
new HollowAPIGenerator(apiClassName, packageName, writeEngine).generateFiles(directory);
```

The main design question is how to indicate which classes should be added (how retrieveClasses method will collect them), I see 3 possible ways to do that:

- specify packagesToScan in buildscript and task will add all classes from these packages
- same as previous, but add only classes that is annotated with some new annotation - `@HollowEntity` ?
- annotations only

I don't like the 3rd one at all, 1st one seems the easiest, but may be not very comfortable for end-users, I like the 2nd one, but it needs new annotation, which should be placed in `com.netflix.hollow:hollow` artifact. I guess there might be some restrictions about this option.

What do you think about it?

**Comment by dkoszewnik** [comment]
Hi Igor, great idea, I believe that we and others would find this useful.

I think we can start with your first suggestion -- specify `packagesToScan` in the buildscript, and the task will add all classes from those packages (recursively?).  It seems to be a reasonable assumption that the POJOs can be grouped under their own package(s) -- if it turns out someone wants to ignore a class from these packages, perhaps we can use the new `@HollowTransient` annotation at the class level to indicate that it should _not_ be serialized, rather than requiring an annotation for inclusion.

Thanks for participating!

**Comment by IgorPerikov** [comment]
plugins are created as standalone projects here:
[gradle](https://github.com/nebula-plugins/nebula-hollow-plugin)
[maven](https://github.com/IgorPerikov/hollow-maven-plugin)
