### ISSUE TITLE
Limit memory footprint on Consumer side

### ISSUE THREAD

**Issue by michalig** [Netflix/hollow#337]
Hi all,

I have a simple question. Is there a way to limit amount of data stored on heap on consumer side by storing only subset of objects (i.e. filtered by their primary key)?

I have a situation where some consumers are interested only in predefined (by PK) subset of objects stored in Hollow, yet I don't see the way to filter out other objects...
I know there is https://hollow.how/tooling/#filtering but this is on attributes level.
There is also a concept of https://hollow.how/tooling/#combining but I don't understand how I could use it on Consumer side?
Another option I was thinking of is https://hollow.how/tooling/#splitting but it seems that it significantly increases memory consumption (or I'm using it in a wrong way).

The only way I can think of is to use separate publishers in producers to publish data to different "namespaces" - like in https://github.com/Netflix/hollow-reference-implementation but I guess there must be a better way.

Thanks in advance :)

**Comment by rajesharma470** [comment]
I happen to have the exact same requirement. Did you finally the way to filter data for consumers?

**Comment by ghost** [comment]
> I have a situation where some consumers are interested only in predefined (by PK) subset of objects stored in Hollow, yet I don't see the way to filter out other objects...

There is nothing out of the box to do this. The [filtering support](https://hollow.how/tooling/#filtering) you identified is all that is available.

> The only way I can think of is to use separate publishers in producers to publish data to different "namespaces"

This is what we do at Netflix. You want to precompute your filtered set so that every consumer doesn't have to pay the price.

You can generalize filtering as map-reduce over a Hollow dataset. To perform map-reduce you need the entire source dataset loaded on heap, thus defeating the purpose of doing it on the consumer.

> Another option I was thinking of is https://hollow.how/tooling/#splitting 

A good thought, but not quite what you want. Splitter is meant for sharding.

If using the primary key based splitter, records will get sharded consistently, but you have no way to say "I want all records with these keys to be in the same shard".

---

I would do one of these, depending on whether I had use-cases that needed the entire unfiltered dataset:

## Option A: `1 + n` Producers

I would use Option A if I had use-cases that needed the unfiltered dataset in addition to cases that needed it filtered.

* 1 producer reading from my source of truth and producing an unfiltered dataset
* n filtering producers — one for each subset of data

You'll use the [combining](https://hollow.how/tooling/#combining) feature that you spotted. Take a look at primary-key based implementations of `HollowCombinerCopyDirector`.

## Option B: `n` filtering producers

I might still use Option A from a simplicity standpoint. Think of Option A like unix pipes. Each step does one thing well. However, you may have reasons to streamline this into a single producer per subset.

* run `n` producers for each filtered subset
* in each producer, filter when querying your source of truth **or** query everything from your source of truth, but filter before adding the record to your dataset

**Comment by ghost** [comment]
Closing. Please re-open if you have more questions.
