### ISSUE TITLE
Problem with BigDecimal serialization

### ISSUE THREAD

**Issue by jan-zywczak** [Netflix/hollow#34]
It looks like serialization of BigDecimal fields is corrupted. Since BigDecimal, for not inflated values, stores its value in transient field, it is not serialized when added to objectMapper. Is it possible to somehow add custom serialization of particular types or rather we should define field in class with different type?

**Comment by dkoszewnik** [comment]
In the case of `BigDecimal`, I think it makes the most sense to define the data as fields in a separate type, then add whatever logic is necessary to interpret these values on the consumer.  

Assuming you can apply knowledge about the possible range of values for you use case, doing things this way may allow you to be more efficient than you would otherwise be if you tried to verbatim serialize the data contained in `BigDecimal`.

**Comment by jan-zywczak** [comment]
Thanks for clarification.
