### ISSUE TITLE
Don't trigger dataUpdated event when 0 sized delta applied.

### ISSUE THREAD

**Issue by alexandrnikitin** [Netflix/hollow#7]
I store a state in my application. I want to update it only when the data changes. My initial intention was to use `HollowUpdateListener` and its `dataUpdated` event. Then update the state only when the event is triggered but it turns out that the event doesn't depend on data content itself and gets triggered all the time. I would expect that when Hollow applies 0 size delta (doesn't change anything) when it won't trigger it. Any other ways how to know that delta doesn't change data?

**Comment by dkoszewnik** [comment]
Hi Alexandr,

In your `HollowUpdateListener`, you can call `updatedLastCycle()` on the `HollowReadStateEngine`.  This returns a boolean indicating whether or not the last delta actually changed anything.

If you find that you are producing a lot of empty deltas, it's perhaps better if you check on the producer whether or not anything actually changed before publishing and announcing the new state.  This can be accomplished using the `hasChangedSinceLastCycle()` call on the `HollowWriteStateEngine`, which also returns a boolean.  If this returns false, then instead of publishing and announcing you can call `writeEngine.resetToLastPrepareForNextCycle()`, which will revert the state engine to the beginning of the current cycle.  In this way, you can avoid ever producing an empty delta.

Thanks,
Drew.

**Comment by alexandrnikitin** [comment]
@dkoszewnik Great! Thank you! Now it makes sense :) Might be worth documenting it .

In case anyone ends up here then this simple code works fine:

```scala
class DataChangedListener extends HollowUpdateListener {
  private[this] var hasNewData = false

  override def hasNewDataSinceMarked: Boolean = hasNewData
  override def markAsProcessed(): Unit = hasNewData = false

  override def refreshFailed(beforeVersion: Long, afterVersion: Long, requestedVersion: Long, failureCause: Throwable): Unit = {}
  override def refreshCompleted(beforeVersion: Long, afterVersion: Long, requestedVersion: Long): Unit = {}
  override def staleReferenceUsageDetected(count: Int): Unit = {}
  override def refreshStarted(currentVersion: Long, requestedVersion: Long): Unit = {}
  override def staleReferenceExistenceDetected(count: Int): Unit = {}
  override def transitionApplied(transition: HollowBlob): Unit = {}

  override def dataUpdated(api: HollowAPI, stateEngine: HollowReadStateEngine, version: Long): Unit = {
    if (stateEngine.updatedLastCycle()) {
      hasNewData = true
    }
  }

  override def dataInitialized(api: HollowAPI, stateEngine: HollowReadStateEngine, version: Long): Unit = {
    hasNewData = true
  }

}
```
